### ISSUE TITLE
Mod loading error

### ISSUE THREAD

**Issue by ghost** [AbsolemJackdaw/EasierVillageTrading#1]
I have a mod loading error with the 1.19 version of the mod.

I attach the crash log.
[crash-2022-08-30_16.47.52-fml.txt](https://github.com/AbsolemJackdaw/EasierVillageTrading/files/9453898/crash-2022-08-30_16.47.52-fml.txt)

**Comment by AbsolemJackdaw** [comment]
the 1.19 version has been coded under 41.0.3 iirc, 41.1 brought breaking changes. 

I advice to update to 1.19.2 like any mod should, given the vast amounts of breaking changes between 1.19 and 1.19.2

the reason mine, or a bunch of mods, haven't updated in a while is because of the breaking changes. theres been like 5 between 1.19 and .2 that i know of. 
.2 should be more stable and less prone to future breaking changes

**Comment by AbsolemJackdaw** [comment]
closing issue as resolved
using an earlier version of forge, or a later version of the mod fixes this issue
